type PracticeItem = {
  id: number;
  text: string;
  translation: string;
  difficulty: 'easy' | 'medium' | 'hard';
  category: string;
  grade: number;
};

// 三年级口语练习（30个）
export const grade3Speaking: PracticeItem[] = [
  // 日常问候
  {
    id: 301,
    text: 'Hello, how are you?',
    translation: '你好，你好吗？',
    difficulty: 'easy',
    category: '日常问候',
    grade: 3,
  },
  {
    id: 302,
    text: 'Good morning!',
    translation: '早上好！',
    difficulty: 'easy',
    category: '日常问候',
    grade: 3,
  },
  {
    id: 303,
    text: 'Good afternoon!',
    translation: '下午好！',
    difficulty: 'easy',
    category: '日常问候',
    grade: 3,
  },
  {
    id: 304,
    text: 'Good evening!',
    translation: '晚上好！',
    difficulty: 'easy',
    category: '日常问候',
    grade: 3,
  },
  {
    id: 305,
    text: 'Good night!',
    translation: '晚安！',
    difficulty: 'easy',
    category: '日常问候',
    grade: 3,
  },
  // 自我介绍
  {
    id: 306,
    text: 'My name is Tom.',
    translation: '我叫汤姆。',
    difficulty: 'easy',
    category: '自我介绍',
    grade: 3,
  },
  {
    id: 307,
    text: 'I am eight years old.',
    translation: '我八岁了。',
    difficulty: 'easy',
    category: '自我介绍',
    grade: 3,
  },
  {
    id: 308,
    text: 'I live in Beijing.',
    translation: '我住在北京。',
    difficulty: 'easy',
    category: '自我介绍',
    grade: 3,
  },
  {
    id: 309,
    text: 'I like apples.',
    translation: '我喜欢苹果。',
    difficulty: 'easy',
    category: '自我介绍',
    grade: 3,
  },
  {
    id: 310,
    text: 'I am a student.',
    translation: '我是一个学生。',
    difficulty: 'easy',
    category: '自我介绍',
    grade: 3,
  },
  // 简单问题
  {
    id: 311,
    text: 'What is your name?',
    translation: '你叫什么名字？',
    difficulty: 'medium',
    category: '简单问题',
    grade: 3,
  },
  {
    id: 312,
    text: 'How old are you?',
    translation: '你多大了？',
    difficulty: 'medium',
    category: '简单问题',
    grade: 3,
  },
  {
    id: 313,
    text: 'Where do you live?',
    translation: '你住在哪里？',
    difficulty: 'medium',
    category: '简单问题',
    grade: 3,
  },
  {
    id: 314,
    text: 'What color do you like?',
    translation: '你喜欢什么颜色？',
    difficulty: 'medium',
    category: '简单问题',
    grade: 3,
  },
  {
    id: 315,
    text: 'What is this?',
    translation: '这是什么？',
    difficulty: 'easy',
    category: '简单问题',
    grade: 3,
  },
  // 简单表达
  {
    id: 316,
    text: 'Thank you very much.',
    translation: '非常感谢。',
    difficulty: 'easy',
    category: '简单表达',
    grade: 3,
  },
  {
    id: 317,
    text: 'You are welcome.',
    translation: '不客气。',
    difficulty: 'easy',
    category: '简单表达',
    grade: 3,
  },
  {
    id: 318,
    text: 'I am sorry.',
    translation: '对不起。',
    difficulty: 'easy',
    category: '简单表达',
    grade: 3,
  },
  {
    id: 319,
    text: 'That is okay.',
    translation: '没关系。',
    difficulty: 'easy',
    category: '简单表达',
    grade: 3,
  },
  {
    id: 320,
    text: 'Nice to meet you.',
    translation: '很高兴见到你。',
    difficulty: 'medium',
    category: '简单表达',
    grade: 3,
  },
  // 日常活动
  {
    id: 321,
    text: 'I go to school by bus.',
    translation: '我坐公交车去上学。',
    difficulty: 'medium',
    category: '日常活动',
    grade: 3,
  },
  {
    id: 322,
    text: 'I eat breakfast at seven.',
    translation: '我七点吃早餐。',
    difficulty: 'medium',
    category: '日常活动',
    grade: 3,
  },
  {
    id: 323,
    text: 'I watch TV in the evening.',
    translation: '我晚上看电视。',
    difficulty: 'medium',
    category: '日常活动',
    grade: 3,
  },
  {
    id: 324,
    text: 'I play football with my friends.',
    translation: '我和朋友踢足球。',
    difficulty: 'medium',
    category: '日常活动',
    grade: 3,
  },
  {
    id: 325,
    text: 'I do my homework after school.',
    translation: '放学后我做作业。',
    difficulty: 'medium',
    category: '日常活动',
    grade: 3,
  },
  {
    id: 326,
    text: 'I go to bed at nine.',
    translation: '我九点睡觉。',
    difficulty: 'medium',
    category: '日常活动',
    grade: 3,
  },
  {
    id: 327,
    text: 'I read books on Sunday.',
    translation: '我周日读书。',
    difficulty: 'medium',
    category: '日常活动',
    grade: 3,
  },
  {
    id: 328,
    text: 'I help my mother at home.',
    translation: '我在家帮妈妈。',
    difficulty: 'medium',
    category: '日常活动',
    grade: 3,
  },
  {
    id: 329,
    text: 'I have lunch at school.',
    translation: '我在学校吃午餐。',
    difficulty: 'medium',
    category: '日常活动',
    grade: 3,
  },
  {
    id: 330,
    text: 'I like swimming very much.',
    translation: '我非常喜欢游泳。',
    difficulty: 'medium',
    category: '日常活动',
    grade: 3,
  },
];

// 四年级口语练习（35个）
export const grade4Speaking: PracticeItem[] = [
  // 日常对话
  {
    id: 401,
    text: 'How are you doing today?',
    translation: '你今天怎么样？',
    difficulty: 'medium',
    category: '日常对话',
    grade: 4,
  },
  {
    id: 402,
    text: 'I am fine, thank you.',
    translation: '我很好，谢谢。',
    difficulty: 'medium',
    category: '日常对话',
    grade: 4,
  },
  {
    id: 403,
    text: 'See you tomorrow.',
    translation: '明天见。',
    difficulty: 'easy',
    category: '日常对话',
    grade: 4,
  },
  {
    id: 404,
    text: 'Have a nice day!',
    translation: '祝你今天愉快！',
    difficulty: 'easy',
    category: '日常对话',
    grade: 4,
  },
  {
    id: 405,
    text: 'How is the weather today?',
    translation: '今天天气怎么样？',
    difficulty: 'medium',
    category: '日常对话',
    grade: 4,
  },
  // 家庭介绍
  {
    id: 406,
    text: 'I have a happy family.',
    translation: '我有一个幸福的家庭。',
    difficulty: 'medium',
    category: '家庭介绍',
    grade: 4,
  },
  {
    id: 407,
    text: 'There are four people in my family.',
    translation: '我家有四口人。',
    difficulty: 'medium',
    category: '家庭介绍',
    grade: 4,
  },
  {
    id: 408,
    text: 'My father is a doctor.',
    translation: '我爸爸是医生。',
    difficulty: 'medium',
    category: '家庭介绍',
    grade: 4,
  },
  {
    id: 409,
    text: 'My mother is a teacher.',
    translation: '我妈妈是老师。',
    difficulty: 'medium',
    category: '家庭介绍',
    grade: 4,
  },
  {
    id: 410,
    text: 'I love my family very much.',
    translation: '我非常爱我的家人。',
    difficulty: 'medium',
    category: '家庭介绍',
    grade: 4,
  },
  // 学校生活
  {
    id: 411,
    text: 'What subjects do you like?',
    translation: '你喜欢什么科目？',
    difficulty: 'medium',
    category: '学校生活',
    grade: 4,
  },
  {
    id: 412,
    text: 'I like English and Math.',
    translation: '我喜欢英语和数学。',
    difficulty: 'medium',
    category: '学校生活',
    grade: 4,
  },
  {
    id: 413,
    text: 'Our classroom is big and bright.',
    translation: '我们的教室又大又明亮。',
    difficulty: 'medium',
    category: '学校生活',
    grade: 4,
  },
  {
    id: 414,
    text: 'My favorite subject is music.',
    translation: '我最喜欢的科目是音乐。',
    difficulty: 'medium',
    category: '学校生活',
    grade: 4,
  },
  {
    id: 415,
    text: 'We have lunch at twelve.',
    translation: '我们十二点吃午餐。',
    difficulty: 'medium',
    category: '学校生活',
    grade: 4,
  },
  // 爱好兴趣
  {
    id: 416,
    text: 'What is your hobby?',
    translation: '你的爱好是什么？',
    difficulty: 'medium',
    category: '爱好兴趣',
    grade: 4,
  },
  {
    id: 417,
    text: 'My hobby is reading books.',
    translation: '我的爱好是读书。',
    difficulty: 'medium',
    category: '爱好兴趣',
    grade: 4,
  },
  {
    id: 418,
    text: 'I like playing basketball.',
    translation: '我喜欢打篮球。',
    difficulty: 'medium',
    category: '爱好兴趣',
    grade: 4,
  },
  {
    id: 419,
    text: 'I enjoy listening to music.',
    translation: '我喜欢听音乐。',
    difficulty: 'medium',
    category: '爱好兴趣',
    grade: 4,
  },
  {
    id: 420,
    text: 'I like drawing pictures.',
    translation: '我喜欢画画。',
    difficulty: 'medium',
    category: '爱好兴趣',
    grade: 4,
  },
  // 日常活动
  {
    id: 421,
    text: 'I usually get up at six thirty.',
    translation: '我通常六点半起床。',
    difficulty: 'medium',
    category: '日常活动',
    grade: 4,
  },
  {
    id: 422,
    text: 'I brush my teeth every morning.',
    translation: '我每天早上刷牙。',
    difficulty: 'medium',
    category: '日常活动',
    grade: 4,
  },
  {
    id: 423,
    text: 'I clean my room on weekends.',
    translation: '我周末打扫房间。',
    difficulty: 'medium',
    category: '日常活动',
    grade: 4,
  },
  {
    id: 424,
    text: 'I go shopping with my mother.',
    translation: '我和妈妈去购物。',
    difficulty: 'medium',
    category: '日常活动',
    grade: 4,
  },
  {
    id: 425,
    text: 'I play games with my friends.',
    translation: '我和朋友玩游戏。',
    difficulty: 'medium',
    category: '日常活动',
    grade: 4,
  },
  {
    id: 426,
    text: 'I visit my grandparents on Sunday.',
    translation: '我周日去看望祖父母。',
    difficulty: 'medium',
    category: '日常活动',
    grade: 4,
  },
  {
    id: 427,
    text: 'I water the flowers every day.',
    translation: '我每天浇花。',
    difficulty: 'medium',
    category: '日常活动',
    grade: 4,
  },
  {
    id: 428,
    text: 'I take a shower in the evening.',
    translation: '我晚上洗澡。',
    difficulty: 'medium',
    category: '日常活动',
    grade: 4,
  },
  {
    id: 429,
    text: 'I do exercise every morning.',
    translation: '我每天早上锻炼。',
    difficulty: 'medium',
    category: '日常活动',
    grade: 4,
  },
  {
    id: 430,
    text: 'I make my bed before breakfast.',
    translation: '我早餐前整理床铺。',
    difficulty: 'medium',
    category: '日常活动',
    grade: 4,
  },
  // 简单表达
  {
    id: 431,
    text: 'Could you help me, please?',
    translation: '请帮帮我好吗？',
    difficulty: 'medium',
    category: '礼貌表达',
    grade: 4,
  },
  {
    id: 432,
    text: 'What time is it now?',
    translation: '现在几点了？',
    difficulty: 'easy',
    category: '简单问题',
    grade: 4,
  },
  {
    id: 433,
    text: 'Can I ask a question?',
    translation: '我可以问个问题吗？',
    difficulty: 'medium',
    category: '礼貌表达',
    grade: 4,
  },
  {
    id: 434,
    text: 'May I come in?',
    translation: '我可以进来吗？',
    difficulty: 'medium',
    category: '礼貌表达',
    grade: 4,
  },
  {
    id: 435,
    text: 'Please wait a moment.',
    translation: '请等一下。',
    difficulty: 'easy',
    category: '礼貌表达',
    grade: 4,
  },
];

// 五年级口语练习（40个）
export const grade5Speaking: PracticeItem[] = [
  // 日常对话
  {
    id: 501,
    text: 'What did you do yesterday?',
    translation: '你昨天做了什么？',
    difficulty: 'medium',
    category: '日常对话',
    grade: 5,
  },
  {
    id: 502,
    text: 'I went to the park with my friends.',
    translation: '我和朋友去公园了。',
    difficulty: 'medium',
    category: '日常对话',
    grade: 5,
  },
  {
    id: 503,
    text: 'What are you going to do this weekend?',
    translation: '这周末你打算做什么？',
    difficulty: 'hard',
    category: '日常对话',
    grade: 5,
  },
  {
    id: 504,
    text: 'I am going to visit my grandparents.',
    translation: '我要去看望我的祖父母。',
    difficulty: 'hard',
    category: '日常对话',
    grade: 5,
  },
  {
    id: 505,
    text: 'Have you ever been to Shanghai?',
    translation: '你去过上海吗？',
    difficulty: 'hard',
    category: '日常对话',
    grade: 5,
  },
  // 描述事物
  {
    id: 506,
    text: 'The book is very interesting.',
    translation: '这本书很有趣。',
    difficulty: 'medium',
    category: '描述事物',
    grade: 5,
  },
  {
    id: 507,
    text: 'The movie was exciting.',
    translation: '这部电影很精彩。',
    difficulty: 'medium',
    category: '描述事物',
    grade: 5,
  },
  {
    id: 508,
    text: 'The weather is getting warmer.',
    translation: '天气越来越暖和了。',
    difficulty: 'medium',
    category: '描述事物',
    grade: 5,
  },
  {
    id: 509,
    text: 'The city is beautiful and modern.',
    translation: '这座城市美丽又现代。',
    difficulty: 'medium',
    category: '描述事物',
    grade: 5,
  },
  {
    id: 510,
    text: 'The food in this restaurant is delicious.',
    translation: '这家餐厅的食物很好吃。',
    difficulty: 'medium',
    category: '描述事物',
    grade: 5,
  },
  // 表达观点
  {
    id: 511,
    text: 'I think it is a good idea.',
    translation: '我觉得这是个好主意。',
    difficulty: 'medium',
    category: '表达观点',
    grade: 5,
  },
  {
    id: 512,
    text: 'In my opinion, we should study hard.',
    translation: '在我看来，我们应该努力学习。',
    difficulty: 'hard',
    category: '表达观点',
    grade: 5,
  },
  {
    id: 513,
    text: 'I agree with you.',
    translation: '我同意你的看法。',
    difficulty: 'medium',
    category: '表达观点',
    grade: 5,
  },
  {
    id: 514,
    text: 'I disagree with your opinion.',
    translation: '我不同意你的观点。',
    difficulty: 'hard',
    category: '表达观点',
    grade: 5,
  },
  {
    id: 515,
    text: 'I believe we can succeed.',
    translation: '我相信我们能成功。',
    difficulty: 'medium',
    category: '表达观点',
    grade: 5,
  },
  // 计划安排
  {
    id: 516,
    text: 'What are your plans for the summer vacation?',
    translation: '你暑假有什么计划？',
    difficulty: 'hard',
    category: '计划安排',
    grade: 5,
  },
  {
    id: 517,
    text: 'I plan to learn swimming.',
    translation: '我计划学游泳。',
    difficulty: 'medium',
    category: '计划安排',
    grade: 5,
  },
  {
    id: 518,
    text: 'I will visit my uncle next week.',
    translation: '我下周要去看望我的叔叔。',
    difficulty: 'medium',
    category: '计划安排',
    grade: 5,
  },
  {
    id: 519,
    text: 'We are going to have a party.',
    translation: '我们要举办一个聚会。',
    difficulty: 'medium',
    category: '计划安排',
    grade: 5,
  },
  {
    id: 520,
    text: 'I hope to travel to London.',
    translation: '我希望去伦敦旅行。',
    difficulty: 'hard',
    category: '计划安排',
    grade: 5,
  },
  // 经历描述
  {
    id: 521,
    text: 'I had a great time at the party.',
    translation: '我在聚会上玩得很开心。',
    difficulty: 'medium',
    category: '经历描述',
    grade: 5,
  },
  {
    id: 522,
    text: 'I felt very happy yesterday.',
    translation: '昨天我感到很开心。',
    difficulty: 'medium',
    category: '经历描述',
    grade: 5,
  },
  {
    id: 523,
    text: 'I learned a lot from the trip.',
    translation: '我从这次旅行中学到了很多。',
    difficulty: 'medium',
    category: '经历描述',
    grade: 5,
  },
  {
    id: 524,
    text: 'It was an unforgettable experience.',
    translation: '这是一次难忘的经历。',
    difficulty: 'hard',
    category: '经历描述',
    grade: 5,
  },
  {
    id: 525,
    text: 'I enjoyed the beautiful scenery.',
    translation: '我欣赏了美丽的风景。',
    difficulty: 'medium',
    category: '经历描述',
    grade: 5,
  },
  // 学习相关
  {
    id: 526,
    text: 'How do you improve your English?',
    translation: '你是如何提高英语的？',
    difficulty: 'hard',
    category: '学习相关',
    grade: 5,
  },
  {
    id: 527,
    text: 'I practice speaking English every day.',
    translation: '我每天练习说英语。',
    difficulty: 'medium',
    category: '学习相关',
    grade: 5,
  },
  {
    id: 528,
    text: 'Reading helps me learn new words.',
    translation: '阅读帮助我学习新单词。',
    difficulty: 'medium',
    category: '学习相关',
    grade: 5,
  },
  {
    id: 529,
    text: 'I listen to English songs to learn.',
    translation: '我听英文歌来学习。',
    difficulty: 'medium',
    category: '学习相关',
    grade: 5,
  },
  {
    id: 530,
    text: 'I find English grammar a bit difficult.',
    translation: '我觉得英语语法有点难。',
    difficulty: 'hard',
    category: '学习相关',
    grade: 5,
  },
  // 情感表达
  {
    id: 531,
    text: 'I am excited about the trip.',
    translation: '我对这次旅行感到兴奋。',
    difficulty: 'medium',
    category: '情感表达',
    grade: 5,
  },
  {
    id: 532,
    text: 'I feel a little nervous before the test.',
    translation: '考试前我感到有点紧张。',
    difficulty: 'medium',
    category: '情感表达',
    grade: 5,
  },
  {
    id: 533,
    text: 'I am proud of my achievements.',
    translation: '我为我的成就感到骄傲。',
    difficulty: 'medium',
    category: '情感表达',
    grade: 5,
  },
  {
    id: 534,
    text: 'I am worried about my grades.',
    translation: '我担心我的成绩。',
    difficulty: 'medium',
    category: '情感表达',
    grade: 5,
  },
  {
    id: 535,
    text: 'I feel confident about the future.',
    translation: '我对未来充满信心。',
    difficulty: 'medium',
    category: '情感表达',
    grade: 5,
  },
  // 建议请求
  {
    id: 536,
    text: 'Can you give me some advice?',
    translation: '你能给我一些建议吗？',
    difficulty: 'medium',
    category: '建议请求',
    grade: 5,
  },
  {
    id: 537,
    text: 'I suggest you read more books.',
    translation: '我建议你多读书。',
    difficulty: 'medium',
    category: '建议请求',
    grade: 5,
  },
  {
    id: 538,
    text: 'Would you like to join us?',
    translation: '你想加入我们吗？',
    difficulty: 'medium',
    category: '建议请求',
    grade: 5,
  },
  {
    id: 539,
    text: 'Let us work together.',
    translation: '让我们一起工作吧。',
    difficulty: 'medium',
    category: '建议请求',
    grade: 5,
  },
  {
    id: 540,
    text: 'I need your help.',
    translation: '我需要你的帮助。',
    difficulty: 'medium',
    category: '建议请求',
    grade: 5,
  },
];

// 六年级口语练习（40个）
export const grade6Speaking: PracticeItem[] = [
  // 深度对话
  {
    id: 601,
    text: 'What do you think about environmental protection?',
    translation: '你对环境保护有什么看法？',
    difficulty: 'hard',
    category: '深度对话',
    grade: 6,
  },
  {
    id: 602,
    text: 'I believe we should protect our planet.',
    translation: '我相信我们应该保护我们的星球。',
    difficulty: 'hard',
    category: '深度对话',
    grade: 6,
  },
  {
    id: 603,
    text: 'What is your opinion on technology?',
    translation: '你对技术有什么看法？',
    difficulty: 'hard',
    category: '深度对话',
    grade: 6,
  },
  {
    id: 604,
    text: 'Technology has changed our lives dramatically.',
    translation: '技术彻底改变了我们的生活。',
    difficulty: 'hard',
    category: '深度对话',
    grade: 6,
  },
  {
    id: 605,
    text: 'How do you stay healthy?',
    translation: '你是如何保持健康的？',
    difficulty: 'medium',
    category: '深度对话',
    grade: 6,
  },
  // 复杂表达
  {
    id: 606,
    text: 'The more you practice, the better you will become.',
    translation: '你练习得越多，就会变得越好。',
    difficulty: 'hard',
    category: '复杂表达',
    grade: 6,
  },
  {
    id: 607,
    text: 'It is important to balance study and rest.',
    translation: '平衡学习和休息很重要。',
    difficulty: 'hard',
    category: '复杂表达',
    grade: 6,
  },
  {
    id: 608,
    text: 'Never give up on your dreams.',
    translation: '永远不要放弃你的梦想。',
    difficulty: 'hard',
    category: '复杂表达',
    grade: 6,
  },
  {
    id: 609,
    text: 'Success comes from hard work and perseverance.',
    translation: '成功来自努力工作和坚持不懈。',
    difficulty: 'hard',
    category: '复杂表达',
    grade: 6,
  },
  {
    id: 610,
    text: 'Learning is a lifelong journey.',
    translation: '学习是一生的旅程。',
    difficulty: 'hard',
    category: '复杂表达',
    grade: 6,
  },
  // 比较对比
  {
    id: 611,
    text: 'What are the differences between cities and countryside?',
    translation: '城市和乡村有什么不同？',
    difficulty: 'hard',
    category: '比较对比',
    grade: 6,
  },
  {
    id: 612,
    text: 'Cities are busier than the countryside.',
    translation: '城市比乡村更繁忙。',
    difficulty: 'medium',
    category: '比较对比',
    grade: 6,
  },
  {
    id: 613,
    text: 'Which do you prefer, tea or coffee?',
    translation: '你更喜欢茶还是咖啡？',
    difficulty: 'medium',
    category: '比较对比',
    grade: 6,
  },
  {
    id: 614,
    text: 'I prefer tea because it is healthy.',
    translation: '我更喜欢茶，因为它很健康。',
    difficulty: 'medium',
    category: '比较对比',
    grade: 6,
  },
  {
    id: 615,
    text: 'Both options have their advantages.',
    translation: '两个选项各有优缺点。',
    difficulty: 'hard',
    category: '比较对比',
    grade: 6,
  },
  // 原因结果
  {
    id: 616,
    text: 'Why do you think learning English is important?',
    translation: '你认为学习英语为什么重要？',
    difficulty: 'hard',
    category: '原因结果',
    grade: 6,
  },
  {
    id: 617,
    text: 'English helps us communicate with people around the world.',
    translation: '英语帮助我们与世界各地的人交流。',
    difficulty: 'hard',
    category: '原因结果',
    grade: 6,
  },
  {
    id: 618,
    text: 'Because of the rain, we stayed at home.',
    translation: '因为下雨，我们待在家里。',
    difficulty: 'medium',
    category: '原因结果',
    grade: 6,
  },
  {
    id: 619,
    text: 'As a result, we missed the train.',
    translation: '结果，我们错过了火车。',
    difficulty: 'medium',
    category: '原因结果',
    grade: 6,
  },
  {
    id: 620,
    text: 'Due to the heavy traffic, we were late.',
    translation: '由于交通拥堵，我们迟到了。',
    difficulty: 'medium',
    category: '原因结果',
    grade: 6,
  },
  // 假设情景
  {
    id: 621,
    text: 'What would you do if you had a million dollars?',
    translation: '如果你有一百万美元，你会做什么？',
    difficulty: 'hard',
    category: '假设情景',
    grade: 6,
  },
  {
    id: 622,
    text: 'If I had a million dollars, I would travel around the world.',
    translation: '如果我有一百万美元，我会环游世界。',
    difficulty: 'hard',
    category: '假设情景',
    grade: 6,
  },
  {
    id: 623,
    text: 'If it rains tomorrow, we will stay at home.',
    translation: '如果明天下雨，我们就待在家里。',
    difficulty: 'medium',
    category: '假设情景',
    grade: 6,
  },
  {
    id: 624,
    text: 'What would happen if everyone recycled?',
    translation: '如果每个人都回收，会发生什么？',
    difficulty: 'hard',
    category: '假设情景',
    grade: 6,
  },
  {
    id: 625,
    text: 'The world would be much cleaner.',
    translation: '世界会变得更干净。',
    difficulty: 'medium',
    category: '假设情景',
    grade: 6,
  },
  // 文化交流
  {
    id: 626,
    text: 'Tell me about Chinese New Year.',
    translation: '跟我讲讲中国新年。',
    difficulty: 'medium',
    category: '文化交流',
    grade: 6,
  },
  {
    id: 627,
    text: 'Chinese New Year is the most important festival in China.',
    translation: '中国新年是中国最重要的节日。',
    difficulty: 'medium',
    category: '文化交流',
    grade: 6,
  },
  {
    id: 628,
    text: 'People celebrate with family reunions and delicious food.',
    translation: '人们通过家庭团聚和美食来庆祝。',
    difficulty: 'hard',
    category: '文化交流',
    grade: 6,
  },
  {
    id: 629,
    text: 'What are some traditional Chinese festivals?',
    translation: '有哪些中国传统节日？',
    difficulty: 'medium',
    category: '文化交流',
    grade: 6,
  },
  {
    id: 630,
    text: 'We have Spring Festival, Dragon Boat Festival, and Mid-Autumn Festival.',
    translation: '我们有春节、端午节和中秋节。',
    difficulty: 'hard',
    category: '文化交流',
    grade: 6,
  },
  // 未来展望
  {
    id: 631,
    text: 'What do you want to be in the future?',
    translation: '你将来想成为什么样的人？',
    difficulty: 'medium',
    category: '未来展望',
    grade: 6,
  },
  {
    id: 632,
    text: 'I want to be a scientist.',
    translation: '我想成为一名科学家。',
    difficulty: 'medium',
    category: '未来展望',
    grade: 6,
  },
  {
    id: 633,
    text: 'I hope to make a difference in the world.',
    translation: '我希望对世界产生影响。',
    difficulty: 'hard',
    category: '未来展望',
    grade: 6,
  },
  {
    id: 634,
    text: 'My dream is to become a doctor and help people.',
    translation: '我的梦想是成为一名医生，帮助人们。',
    difficulty: 'hard',
    category: '未来展望',
    grade: 6,
  },
  {
    id: 635,
    text: 'I will work hard to achieve my goals.',
    translation: '我会努力实现我的目标。',
    difficulty: 'medium',
    category: '未来展望',
    grade: 6,
  },
  // 复杂建议
  {
    id: 636,
    text: 'I strongly recommend that you read this book.',
    translation: '我强烈推荐你读这本书。',
    difficulty: 'hard',
    category: '复杂建议',
    grade: 6,
  },
  {
    id: 637,
    text: 'It would be better if you practiced more.',
    translation: '如果你多练习会更好。',
    difficulty: 'hard',
    category: '复杂建议',
    grade: 6,
  },
  {
    id: 638,
    text: 'Why not join the English club?',
    translation: '为什么不加入英语俱乐部呢？',
    difficulty: 'medium',
    category: '复杂建议',
    grade: 6,
  },
  {
    id: 639,
    text: 'You might consider taking an online course.',
    translation: '你可以考虑参加在线课程。',
    difficulty: 'hard',
    category: '复杂建议',
    grade: 6,
  },
  {
    id: 640,
    text: 'I suggest we work together on this project.',
    translation: '我建议我们在这个项目上合作。',
    difficulty: 'hard',
    category: '复杂建议',
    grade: 6,
  },
];

// 合并所有口语练习
export const allSpeakingItems: PracticeItem[] = [
  ...grade3Speaking,
  ...grade4Speaking,
  ...grade5Speaking,
  ...grade6Speaking,
];

// 获取指定年级的口语练习
export const getSpeakingByGrade = (grade: number): PracticeItem[] => {
  return allSpeakingItems.filter(item => item.grade === grade);
};
